name: Trigger JitPack Build

on:
  release:
    types:
      - published

jobs:
  trigger-jitpack:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger JitPack Build
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          curl -X POST https://jitpack.io/api/builds/${{ github.repository }}/tags/${TAG_NAME}
