name: Publish to Maven Central

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java & GPG for Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.GPG_SIGNING_PASSPHRASE }}

      - name: Debug Credentials
        run: |
          echo "OSSRH_USERNAME: ${OSSRH_USERNAME:0:4}***"
          echo "OSSRH_PASSWORD: ${OSSRH_PASSWORD:0:4}***"        

      - name: Build and Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        run: |
          ./gradlew clean publish --info --stacktrace